transform_tolerance: 0.35
obstacle_range: 2.5
max_obstacle_height: 2.0
raytrace_range: 3.0
inscribed_radius: 0.325
circumscribed_radius: 0.46
inflation_radius: 0.55
cost_scaling_factor: 10.0
lethal_cost_threshold: 100
observation_topics: base_scan
scan: {sensor_frame: frame_from_message, data_type: PointCloud, expected_update_rate: 0.2, observation_persistence: 0.0, marking: true, clearing: true}